### ISSUE TITLE
Feature request: Support for country and  language code

### ISSUE THREAD

**Issue by soernt** [smartnsoft/FlappyTranslator#1]
Thank you very much for this super simple translation solution. 
We need to support countries where more than one language is spoken. For example Switzerland:
german: de-CH
french: fr-CH
italian: it-CH

Kind regards,
Sörnt

**Comment by ThomasEcalle** [comment]
Hi @soernt , 

Thank you a lot for this feature and your help in building a great translation's tool.
I merged your work, will update the documentation and it would be ok for a new version thanks to you !

Regards,
Thomas
