### ISSUE TITLE
Getting the current locale 

### ISSUE THREAD

**Issue by TarekMedhat** [smartnsoft/FlappyTranslator#11]
`Strings.of(context).currentLocale` doesn't get updated and always returns `"en"` after changing the locale by calling:
`Strings.load(Locale("ar"))`

**Comment by ThomasEcalle** [comment]
Hi

It normally works but  : 

In case you try to **print** the current locale : 
* Did you wait for the **Future** `Strings.load(Locale("ar"))` before requesting `Strings.of(context).currentLocale` ?
Indeed, the `load` method is async and you have to wait for it

In case you try to **show** the current locale on screen :
* Have you well called `setState` (or other state management method) ?
Indeed, if you show something and change it later, you have to redraw your screen in order to see the changes.

Please let me know if none of these solutions work.
I hope I could help you

**Comment by TarekMedhat** [comment]
Hello Thomas,

Thank you for your response.

The UI gets updated by the new strings based on the loaded locale but currentLocale doesn't get updated.

That is because the "of" constructor returns a new object of our class every time which has no clue about the updated _locale variable
```
 static Strings of(BuildContext context) {
    return Localizations.of<Strings>(context, Strings);
  }
```

So, doing the following will print the correct updated currentLanguage since I'm printing using the same reference
```
Strings strings = await Strings.load(Locale("ar"));
              print(strings.currentLanguage);
```
but getting our class from else where with "of" constructor will return a new object with the default locale
```
Strings strings = await Strings.load(Locale("ar"));
              print(Strings.of(context).currentLanguage);
```

To get this fixed we can just make _locale a **static** variable, which what I did and worked for me

>   Strings(Locale locale) {
>     **Strings**._locale = locale;
>     _localizedValues = null;
>   }
> 
>   **static** Locale _locale;
>

**Comment by ThomasEcalle** [comment]
Hmmmm, ok I think I understand better what you mean.

Have you tried the new possibility set `depend_on_context` to false in the pubspec.yaml ?
With something like that for example : 

```
flappy_translator:
  input_file_path: "test.csv"
  output_dir: "lib"
  file_name: "i18n"
  class_name: "I18n"
  delimiter: ","
  start_index: 1
  depend_on_context: false
  use_single_quotes: false
  replace_no_break_spaces: false
```

The generated file will be quite different and your strings would not be using context anymore.

_Bad point_ : you will have to replace all `Strings.of(context).myVariable` with `Strings.myVariable`

But I think that it would fix your issue !

Indeed, `currentLocale` would be accessible as a static variable as you said : 

`Strings.currentLocale`

Please let me know if that helps you.

If not, I will try to fix that when `depend_on_context` is set to true

**Comment by defuncart** [comment]
Hi @TarekMedhat. I cannot seem to reproduce the behavior you mentioned.

```dart
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

import 'i18n.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: [
        const I18nDelegate(),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: I18nDelegate.supportedLocals,
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  const Home({Key key}) : super(key: key);

  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Center(
          child: Column(
            children: <Widget>[
              Text(I18n.of(context).appTitle),
              Text(I18n.of(context).description(var1: "2")),
              Text(I18n.of(context).littleTest(age: 32)),
              Row(
                children: [
                  for (final locale in I18nDelegate.supportedLocals)
                    Expanded(
                      child: RaisedButton(
                        child: Text(locale.toString()),
                        onPressed: () => setState(() {
                          I18n.load(locale);
                        }),
                      ),
                    )
                ],
              )
            ],
          ),
        ),
      ),
    );
  }
}
```

Here each supported locale is a button displayed on the screen. Once I press a button, the corresponding locale is loaded and successfully displayed.

![flappyTranslatorIssue11](https://user-images.githubusercontent.com/13286425/93669016-279ca280-fa91-11ea-80a8-08bc7291c5a7.gif)

Note that [as per example](https://github.com/smartnsoft/FlappyTranslator/blob/master/example/lib/i18n.dart), `_locale` isn't a static variable.

Please let me know if I have missed something or if you can still reproduce.

**Comment by dan-gandolfo** [comment]
> Hmmmm, ok I think I understand better what you mean.
> 
> Have you tried the new possibility set `depend_on_context` to false in the pubspec.yaml ?
> With something like that for example :
> 
> ```
> flappy_translator:
>   input_file_path: "test.csv"
>   output_dir: "lib"
>   file_name: "i18n"
>   class_name: "I18n"
>   delimiter: ","
>   start_index: 1
>   depend_on_context: false
>   use_single_quotes: false
>   replace_no_break_spaces: false
> ```
> 
> The generated file will be quite different and your strings would not be using context anymore.
> 
> _Bad point_ : you will have to replace all `Strings.of(context).myVariable` with `Strings.myVariable`
> 
> But I think that it would fix your issue !
> 
> Indeed, `currentLocale` would be accessible as a static variable as you said :
> 
> `Strings.currentLocale`
> 
> Please let me know if that helps you.
> 
> If not, I will try to fix that when `depend_on_context` is set to true

This solution fix my issue.
Thanks for help

**Comment by defuncart** [comment]
Closing this issue as it does not seem to be reproducible. Please feel free to re-open if you experience any further issues.
