### ISSUE TITLE
Generated mapping varible name causes dart analysis info/warning:

### ISSUE THREAD

**Issue by lingster** [smartnsoft/FlappyTranslator#12]
In the generated map of translations, the varible name is defined as:

`  static Map<String, String> _en_USValues = {`
however this generated the following info/issue in dart analyser:
`info: Name non-constant identifiers using lowerCamelCase. (non_constant_identifier_names at ...`

Can we add an option to remove the underscore in the ${lang} name ?

**Comment by ThomasEcalle** [comment]
Hi @lingster 

Your are right, in order to follow Dart guidelines, these variables should be in camelCase.

I have just fixed that in the new `1.2.1` that you can now test !

Thank you for your feedback :)

**Comment by ThomasEcalle** [comment]
I am sorry I didn't see your PR and I have done it myself..

**Comment by lingster** [comment]
Hi, no problems about not seeing my PR, I will test out the new version later today. Thanks for the prompt reply and building a useful tool! On 24 Jan 2020 08:30, Ecalle Thomas <notifications@github.com> wrote:I am sorry I didn't see your PR and I have done it myself..

**Comment by ThomasEcalle** [comment]
Nice ! You are welcome :)
I close this issue dfor the moment, feel free to re-open it if it is not working as you would like !

**Comment by xalanq** [comment]
`zh_Hans`
It should be
```dart
Locale("zh", "Hans");
```
but not
```dart
Locale("zhHans");
```

**Comment by ThomasEcalle** [comment]
Damn, absolutely sorry for that

Fixed in 1.2.2 right now !

**Comment by lingster** [comment]
Would it be useful to create a functional test? So maybe generate the flappy code from the examples and this could be used as the test case. If someone makes changes there should be a test case to compare the generated code vs the version in git. This would then help to verify the change is good.
