### ISSUE TITLE
Make _getText public

### ISSUE THREAD

**Issue by stefanop1** [smartnsoft/FlappyTranslator#15]
Please, I need to get the localized version of a key contained in a String

**Comment by SSebigo** [comment]
Or maybe have a way to get a translation via bracket notation:

``` Dart
I18n.of(context)['myTranslation']
```

**Comment by stefanop1** [comment]
This can be very handful.

Il sab 7 mar 2020, 13:11 François <notifications@github.com> ha scritto:

**Comment by bounty1342** [comment]
Hi,
I18n.of(context)[var]; would be a real benefit !
It will handle situations where the key could change, whitout the boilerplate of writing of switch case just for that. (Exception handling for exemple)

**Comment by bounty1342** [comment]
> > Hi,
> > I18n.of(context)[var]; would be a real benefit !
> > It will handle situations where the key could change, without the boilerplate of writing switch case just for that. (Exception handling for exemple)
> 
> 
> Also, you can write an extension to implement this behavior in the meantime :
> ``` dart
> extension I18nExtension on I18n {
>   String text(String key) {
>     return this._getText(key);
>   }
> 
>   Map<String, String> map() {
>     return I18n._allValues[this.currentLocale.toString()];
>   }
> }
> ```
> 
> ``` dart
> var trad = I18n.of(context).accesRestricted;
> var tradGetText = I18n.of(context).text('accesRestricted');
> var tradGetMap = I18n.of(context).map()['accesRestricted'];
> 
> print(trad);
> print(tradGetText);
> print(tradGetMap);
> ```
> 
> Hope this help for the time being.
> Regards,

Not working. Please update the lib :)

**Comment by defuncart** [comment]
@bounty1342 @stefanop1 This is something that I also actually need for a current project so I put this MR together: https://github.com/smartnsoft/FlappyTranslator/pull/19 Please feel free to contribute.
