### ISSUE TITLE
Problems with file generation

### ISSUE THREAD

**Issue by rizz1995** [smartnsoft/FlappyTranslator#21]
Hi there,
I've use this plugin for several months now with no issues. However, I recently encounter some problems. When I try to generate the dart file, it will be generated on the root directory instead of the designated output path & the generated file now doesn't follow the values set on the pubspec.yaml (I set depend_on_context as false but the file now do depend on context). Is there any solution for this problem?

**Comment by defuncart** [comment]
@rizz1995 Can you produce a minimal working example? I've been using this package for months too (personal and professional projects) and have not experienced the issues you mention.

**Comment by rizz1995** [comment]
Never mind, I have already found the problem. Turns out it downgraded itself to older version when I try to do testing (I use Flutter 1.9.1+hotfix6). I will close this issue now.
