### ISSUE TITLE
Run package with languages lacking language codes?

### ISSUE THREAD

**Issue by TJMusiitwa** [smartnsoft/FlappyTranslator#23]
Hey there so there's this application that I am building that is meant to relay information in a number of languages given that it's to serve a country of multi languages and while some languages will come off as easy e.g. Swahili, English, kinyarwanda, Arabic etc... There are some languages that don't have common language codes...

So I was wondering if this package will be able to run with languages where I am able to provide all the translations but don't have language codes (can I be able to define my own codes)

PS some of these are languages supported by Google even in  _search_?

**Comment by defuncart** [comment]
@TJMusiitwa This package should work with the [following language codes](https://api.flutter.dev/flutter/flutter_localizations/GlobalMaterialLocalizations-class.html) and any regional variants (i.e. en_GB, en_US).

However, even if a language isn't here included (for instance ga, Gaeilge/Irish), it can still be loaded by flappy using `I18n.load(Locale('ga')`. In this case, you could initially set the app's default language to device language or a fallback (i.e. English), and allow the user to change the language in settings.

With regard to defining your own codes, please report back if this works! It seems possible using the ga example above.

Hope this (somewhat) answers your question.

**Comment by defuncart** [comment]
@TJMusiitwa I can confirm that custom language codes or does not supported by Google in Flutter can be loaded using flappy_translator, for instance, ga_IE or cy_GB.

As mentioned [here](https://stackoverflow.com/a/63133961), your app, however, will crash if you do not have a `GlobalMaterialLocalizations` delegate for these languages. [Here](https://github.com/flutter/website/blob/master/examples/internationalization/add_language/lib/main.dart) is an example of a custom GlobalMaterialLocalizations delegate, while [here](https://github.com/defuncart/bratacha) is an app that I'm developing which is localized in ga and cy, two languages not supported by default.

**Comment by defuncart** [comment]
Closing issue as original question has been answered. Please re-open if you experience any issues.
