### ISSUE TITLE
I18n.of(context) returns null

### ISSUE THREAD

**Issue by speller** [smartnsoft/FlappyTranslator#25]
My code:

```
import 'dart:io';

import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

import './i18n.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    var i18n = I18n.of(context);

    return MaterialApp(
      title: i18n.appTitle,
      supportedLocales: I18nDelegate.supportedLocals,
      initialRoute: '',
      routes: [],
    );
  }
}
```

I'm getting the following exception when running it:

> I/flutter ( 5741): The getter 'appTitle' was called on null.

What I'm doing wrong?

**Comment by defuncart** [comment]
@speller You need to set up the localization delegates as per [documentation](https://github.com/smartnsoft/FlappyTranslator#use-the-i18n-generated-file). You can take a look at this [example](https://github.com/smartnsoft/FlappyTranslator/blob/master/example/lib/main.dart) for more info.

**Comment by defuncart** [comment]
Closing this issue as code does not follow documentation or example. Please feel free to re-open if you experience any further issues.
