### ISSUE TITLE
Migrate to Null Safety

### ISSUE THREAD

**Issue by defuncart** [smartnsoft/FlappyTranslator#42]
Once the dependencies [dart_style](https://pub.dev/packages/dart_style) and [excel](https://pub.dev/packages/excel) are migrated to null safety, then flappy_translator will also be migrated.

Related issues:
[excel - Null safety migration](https://github.com/justkawal/excel/issues/79)
[dart_style - Migrate to null safety](https://github.com/dart-lang/dart_style/issues/978)

![Bildschirmfoto 2021-03-04 um 16 00 00](https://user-images.githubusercontent.com/13286425/109983169-df9dcf00-7d02-11eb-8453-9de2b9de3b93.png)

**Comment by justkawal** [comment]
@defuncart 
Hey there,

We have started migration to null-safety and soon an update will be available: [`Null-safety`](https://github.com/justkawal/excel/milestone/1)

~ Best
~ Kawaljeet Singh
~ Long Live 🔥pen Source

**Comment by ivatar39** [comment]
> @defuncart
> Hey there,
> 
> We have started migration to null-safety and soon an update will be available: [`Null-safety`](https://github.com/justkawal/excel/milestone/1)
> 
> ~ Best
> ~ Kawaljeet Singh
> ~ Long Live 🔥pen Source

Are there any updates on this issue?

**Comment by justkawal** [comment]
@ivatar39 
Expected migration by last week of march.

Thanks

**Comment by defuncart** [comment]
As [`dart_style`](https://pub.dev/packages/dart_style) has been ported to null safety, and there is a work in progress on [`excel`](https://github.com/justkawal/excel/tree/null-safety), I have began to migrate `flappy_translator` on the branch [`feature/null_safety`](https://github.com/smartnsoft/FlappyTranslator/tree/feature/null-safety).

Once `excel` has an official null safety release, and `flappy_translator` has been thoroughly tested, a new version will be published. In the meantime, if anyone urgently needs to use `flappy_translator` with null safety, you can depend on this repo in `pubspec.yaml`:

```yaml
flappy_translator:
    git:
      url: https://github.com/smartnsoft/FlappyTranslator.git
      version: 2.0.0-nullsafety.0
```

**Comment by justkawal** [comment]
@defuncart 
Null-safe version of Excel is available on [excel null-safe](https://pub.dev/packages/excel/versions/2.0.0-null-safety)

Found issues !! ,   you are welcome to re-open the issue on: https://github.com/justkawal/excel/issues/79

~ Best
~ Kawal

**Comment by lukaskurz** [comment]
> As [`dart_style`](https://pub.dev/packages/dart_style) has been ported to null safety, and there is a work in progress on [`excel`](https://github.com/justkawal/excel/tree/null-safety), I have began to migrate `flappy_translator` on the branch [`feature/null_safety`](https://github.com/smartnsoft/FlappyTranslator/tree/feature/null-safety).
> 
> Once `excel` has an official null safety release, and `flappy_translator` has been thoroughly tested, a new version will be published. In the meantime, if anyone urgently needs to use `flappy_translator` with null safety, you can depend on this branch in `pubspec.yaml`:
> 
> ```yaml
> flappy_translator:
>   git:
>     url: https://github.com/smartnsoft/FlappyTranslator.git
>     ref: feature/null-safety
> ```

This branch is no longer usable, since the `null-safety` branch on the excel repo has been removed. Can you update the dependency to use the new 2.0.0-prerelease of excel ?

**Comment by defuncart** [comment]
> This branch is no longer usable, since the `null-safety` branch on the excel repo has been removed. Can you update the dependency to use the new 2.0.0-prerelease of excel ?

Just updated, please pull latest changes :)

**Comment by defuncart** [comment]
Note that the branch `feature/null-safety` has been removed. Please use the version `2.0.0-nullsafety.0` until an official 2.0.0 version is release to pub.dev.

```
flappy_translator:
    git:
      url: https://github.com/smartnsoft/FlappyTranslator.git
      version: 2.0.0-nullsafety.0
```

**Comment by defuncart** [comment]
A pre-release version has been updated to [pub.dev](https://pub.dev/packages/flappy_translator/versions/2.0.0-nullsafety.1).

```
dev_dependencies:
  flappy_translator: 2.0.0-nullsafety.1
```

If you incur any issues, please file issues :) Once Excel has an official release, and after more testing on flappy_translator, 2.0.0 will be released.

**Comment by defuncart** [comment]
An updated pre-release has been pushed

```yaml
dev_dependencies:
  flappy_translator: 2.0.0-nullsafety.2
```

Please file issues if you occur any problems :)

**Comment by FauconSpartiate** [comment]
`excel` is null safe on the stable track since `2.0.1`, so if the version gets upgraded to this minimum, `flappy_translator` will also be null safe on stable.

**Comment by defuncart** [comment]
Resolving this issue as `flappy_translator` officially now has a `2.0.0` release 🥳
