### ISSUE TITLE
[Linter] Some linter issues

### ISSUE THREAD

**Issue by bounty1342** [smartnsoft/FlappyTranslator#49]
Ignore or fix :
sort_constructors_first
always_specify_types

Fix : 
prefer_const_constructors
```
  static final Set<Locale> supportedLocals = {
    Locale('en', 'US'),
    Locale('fr', 'FR'),
  };
```

Regards

**Comment by defuncart** [comment]
@bounty1342 What version of `flappy_translator` are you using? And what analyzer settings are you using? Even with pedantic I haven't seen `prefer_const_constructors` warning for `supportedLocals`.

I'll take a deeper look into this. In the meantime you can [update](https://dart.dev/guides/language/analysis-options#the-analysis-options-file) `analysis_options.yaml`:

```yml
analyzer:
  exclude: lib/i18n.dart
```

**Comment by bounty1342** [comment]
Hi,

Thanks you for looking into this.
Fyi, excluding from the analyser remove the auto-import feature.
So not very practical to manually import the class each time you use it 😉

Regards

**Comment by bounty1342** [comment]
There is also this one : "avoid_escaping_inner_quotes".

**Comment by bounty1342** [comment]
@defuncart :

>  flappy_translator: ^2.0.0-nullsafety.1
>   lint: ^1.5.3

**Comment by defuncart** [comment]
@bounty1342 Using the package's example, I cannot reproduce these warnings. [bugfix/linter-issues](https://github.com/smartnsoft/FlappyTranslator/tree/bugfix/linter-issues)

Can you provide a minimal reproducible example?

**Comment by bounty1342** [comment]
Hi @defuncart, 
you can find a minimal projet there :
[test_flappy.zip](https://github.com/smartnsoft/FlappyTranslator/files/6532254/test_flappy.zip)

![Screenshot 2021-05-24 at 14 20 47](https://user-images.githubusercontent.com/6307253/119347026-3defa380-bc9b-11eb-974d-6c579e301f5d.png)
![Screenshot 2021-05-24 at 14 21 03](https://user-images.githubusercontent.com/6307253/119347063-46e07500-bc9b-11eb-9c18-0ee5f46f1097.png)

Concerning the linting exclusion, there is an open issue since 2016 : https://github.com/dart-lang/sdk/issues/57389
But in the meantime, it also exclude it from the analyser, forbidding import.

Pedantic define only a subset of the linting rules :
- https://pub.dev/packages/lint#comparison-to-packagepedantic

If you could just add the one below to //ignore_for_file: it will avoid lint errors for those without breaking anything :)

```
avoid_escaping_inner_quotes
prefer_const_constructors
sort_constructors_first
always_specify_types
```
So if I understand correctly change the line in FlappyTranslator/lib/src/services/code_generation/template.dart :
`// ignore_for_file: public_member_api_docs, prefer_single_quotes, avoid_escaping_inner_quotes, prefer_const_constructors, sort_constructors_first, always_specify_types`

Regards

**Comment by defuncart** [comment]
@bounty1342 Thanks for the detailed MRE. Can you test if this fix solves this issue for you?

```yaml
flappy_translator:
  git:
    url: https://github.com/smartnsoft/FlappyTranslator
    ref: bugfix/linter-issues
```

**Comment by bounty1342** [comment]
Hi,

Thanks, it does fix the linting issues.

Thank you.

**Comment by defuncart** [comment]
@bounty1342 I've pushed pre-release [2.0.0-nullsafety.2](https://pub.dev/packages/flappy_translator/versions/2.0.0-nullsafety.2). Let me know if you spot another other issues.
