### ISSUE TITLE
How to manually set the locale?

### ISSUE THREAD

**Issue by lingster** [smartnsoft/FlappyTranslator#5]
Hi, I've just started to use this in my flutter app, but I wanted to be able to let the user choose the locale. If I create a dropdown list of supported locales how can I get I18n/I18nDelegate to reload for that locale? I've tried:
`Ì18n.load(Locale("fr"));`

but this does not work.

**Comment by ThomasEcalle** [comment]
Hi 

If "fr" is one of the languages you put in your CSV, then `I18n.load(Locale("fr"));` should work.
But did you correctly call `setState()` in your widget ?

`I18n.load(Locale("fr"));` load the new strings but, in order to show them instead the one already shown, you have to re-draw the view (using for example a Stateful widget and setState(), but any re-draw pattern would be fine.

**Comment by lingster** [comment]
Hi, thanks it seems that I was not calling setState() to redraw the screen. Translation is working nicely now!

**Comment by ThomasEcalle** [comment]
Nice to hear ! :)

**Comment by leemuljadi** [comment]
Hi @lingster @ThomasEcalle , I need to implement this in my app as well. Is there any sample code? Cause I don't know where to put the setState(), since I want to create a segmented control that will change the whole language in the app. Thanks!

**Comment by ThomasEcalle** [comment]
Hi @leemuljadi,

Here is an exemple :

Given a `pubspec.yaml` with this configuration :

```
flappy_translator:
  input_file_path: "test.csv"
  output_dir: "lib"
  file_name: "i18n"
  class_name: "I18n"
  delimiter: ","
  start_index: 1
  depend_on_context: true
  use_single_quotes: false
  replace_no_break_spaces: false
```

And this .CSV file :

```
keys,fr,en,es,de_CH
appTitle,Ma super application,My awesome application,Mi gran application,Meine tolle App
subtitle,Un sous titre,A subtitle,Un subtitulò,Ein Untertitel
description,Un texte avec une variable : %1$s,Text with a variable: %1$s,Un texto con una variable : %1$s,Text mit einer Variable: %1$s
littleTest,"Voici, pour l'exemple, ""un test"" avec la variable %age$d","Here is, for the example, ""a test"" with the variable %age$d","Aqui esta, por ejemplo, ""una prueba"" con la variable %age$d","Hier ist, zum Beispiel, ""ein Test"" mit der Variable %age$d"
```

Here is a simple code with a SegmentedControl that enable the user to change the Locale easily : 

```
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:flutter_localizations/flutter_localizations.dart';

import 'i18n.dart';

void main() => runApp(MyApp());

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      localizationsDelegates: [
        const I18nDelegate(),
        GlobalMaterialLocalizations.delegate,
        GlobalWidgetsLocalizations.delegate,
      ],
      supportedLocales: I18nDelegate.supportedLocals,
      home: Home(),
    );
  }
}

class Home extends StatefulWidget {
  @override
  _HomeState createState() => _HomeState();
}

class _HomeState extends State<Home> {
  void _changeLocale(Locale locale) {
    setState(() {
      I18n.load(locale);
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Center(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: <Widget>[
              CupertinoSegmentedControl(
                children: {
                  0: Padding(child: Text("FR"), padding: EdgeInsets.all(5),),
                  1: Padding(child: Text("EN"), padding: EdgeInsets.all(5),),
                  2: Padding(child: Text("ES"), padding: EdgeInsets.all(5),),
                  3: Padding(child: Text("DE"), padding: EdgeInsets.all(5),),
                },
                onValueChanged: (int index) {
                  switch (index) {
                    case 0:
                      _changeLocale(Locale("fr"));
                      break;
                    case 1:
                      _changeLocale(Locale("en"));
                      break;
                    case 2:
                      _changeLocale(Locale("es"));

                      break;
                    default:
                      _changeLocale(Locale('de', 'CH'));
                      break;
                  }
                },
              ),
              Text(I18n.of(context).appTitle),
              Text(I18n.of(context).description(var1: "2")),
              Text(I18n.of(context).littleTest(age: 32)),
            ],
          ),
        ),
      ),
    );
  }
}

```

Hope it will help :)

**Comment by leemuljadi** [comment]
Hi @ThomasEcalle, it does work thanks so much for your help! Btw do you know how do I set the state globally? Cause I want to change the whole app text not only in one widget. 
And also I try to add: 
int _selectedSegment = 0;

void _changeLocale(Locale locale, int index) {
      setState(() {
        _selectedSegment = index;
        I18n.load(locale);
      });
  }

CupertinoSegmentedControl(
                      selectedColor: AppColor.secondary,
                      unselectedColor: AppColor.background,
                      groupValue: _selectedSegment,
                      children: {
                        0: Text("FR"),
                        1: Text("EN"),
                        2: Text("ES"),
                        3: Text("DE"),
                      },
                      onValueChanged: (int index) {
                        switch (index) {
                          case 0:
                            _changeLocale(Locale("fr"), 0);
                            break;
                          case 1:
                            _changeLocale(Locale("en"), 1);
                            break;
                          case 2:
                            _changeLocale(Locale("es"), 2);
                            break;
                          default:
                            _changeLocale(Locale('de', 'CH'), 3);
                            break;
                        }
                      },
                    ),

groupValue parameter to change color of the current selected segment, but it just make it buggy and the color doesn't switch over to other segment. Do you know how resolve this?

Thanks!

**Comment by leemuljadi** [comment]
Hi @ThomasEcalle, it does work thanks so much for your help! Btw do you know how do I set the state globally? Cause I want to change the whole app text not only in one widget.

**Comment by leemuljadi** [comment]
Hi @ThomasEcalle, it does work thanks so much for your help! But when I try the i18n file through running the 'flutter pub get" it doesn't created that file. What do I need to fix here?

Btw any suggestion to set the state globally? Cause I need to change the whole app text.
