### ISSUE TITLE
Its not working with latest flutter sdk 3.0.4 stable 

### ISSUE THREAD

**Issue by parmeetmaster** [smartnsoft/FlappyTranslator#56]
`b get
Running "flutter pub get" in jaysecurity...                     
Because no versions of flappy_translator match >2.0.0-nullsafety.3 <3.0.0 and flappy_translator 2.0.0-nullsafety.3 depends on excel ^2.0.0-null-safety-3, flappy_translator ^2.0.0-nullsafety.3 requires excel ^2.0.0-null-safety-3.
And because no versions of excel match >2.0.0-null-safety-3 <3.0.0, flappy_translator ^2.0.0-nullsafety.3 requires excel 2.0.0-null-safety-3.
And because excel 2.0.0-null-safety-3 depends on xml ^5.0.2 and flutter_svg >=1.1.0 depends on xml ^6.0.1, flappy_translator ^2.0.0-nullsafety.3 is incompatible with flutter_svg >=1.1.0.
So, because jaysecurity depends on both flutter_svg ^1.1.1+1 and flappy_translator ^2.0.0-nullsafety.3, version solving failed.
pub get failed (1; So, because jaysecurity depends on both flutter_svg ^1.1.1+1 and flappy_translator ^2.0.0-nullsafety.3, version solving failed.)`

**Comment by defuncart** [comment]
This looks like an issue due to dependency `excel` and thus transitive dependency `xml`. You could try overriding `xml` dependency in pubspec:

```yaml
dependency_overrides:
  xml: ^5.0.2
```

**Comment by FauconSpartiate** [comment]
@parmeetmaster @defuncart 
This issue is fixed, `excel` has been updated some time ago, fixing its constraints to old dependencies in `2.0.1`. 
This issue can be closed.
